export const    
    LOGIN_START     = 'LOGIN_START',
    LOGIN_FAIL      = 'LOGIN_FAIL',
    LOGIN_SUCCESS   = 'LOGIN_SUCCESS', 
    LOGIN_CLEAN     = 'LOGIN_CLEAN',
    SAVE_USER       = 'SAVE_USER',

    // SIGN_UP
    SIGN_UP_START     = 'SIGN_UP_START',
    SIGN_UP_FAIL      = 'SIGN_UP_FAIL',
    SIGN_UP_SUCCESS   = 'SIGN_UP_SUCCESS', 
    SIGN_UP_CLEAN     = 'SIGN_UP_CLEAN',

    SERVICE_HISTORY_START     = 'SERVICE_HISTORY_START',
    SERVICE_HISTORY_FAIL      = 'SERVICE_HISTORY_FAIL',
    SERVICE_HISTORY_SUCCESS   = 'SERVICE_HISTORY_SUCCESS', 
    SERVICE_HISTORY_CLEAN     = 'SERVICE_HISTORY_CLEAN',

    PROFILE_UPDATE_START     = 'PROFILE_UPDATE_START',
    PROFILE_UPDATE_FAIL      = 'PROFILE_UPDATE_FAIL',
    PROFILE_UPDATE_SUCCESS   = 'PROFILE_UPDATE_SUCCESS', 
    PROFILE_UPDATE_CLEAN     = 'PROFILE_UPDATE_CLEAN',

    CHANGE_PASSWORD_START     = 'CHANGE_PASSWORD_START',
    CHANGE_PASSWORD_FAIL      = 'CHANGE_PASSWORD_FAIL',
    CHANGE_PASSWORD_SUCCESS   = 'CHANGE_PASSWORD_SUCCESS', 
    CHANGE_PASSWORD_CLEAN     = 'CHANGE_PASSWORD_CLEAN',

    ALL_SERVICES_START     = 'ALL_SERVICES_START',
    ALL_SERVICES_FAIL      = 'ALL_SERVICES_FAIL',
    ALL_SERVICES_SUCCESS   = 'ALL_SERVICES_SUCCESS', 
    ALL_SERVICES_CLEAN     = 'ALL_SERVICES_CLEAN',

    SERVICE_REQUEST_START     = 'SERVICE_REQUEST_START',
    SERVICE_REQUEST_FAIL      = 'SERVICE_REQUEST_FAIL',
    SERVICE_REQUEST_SUCCESS   = 'SERVICE_REQUEST_SUCCESS', 
    SERVICE_REQUEST_CLEAN     = 'SERVICE_REQUEST_CLEAN',

    PROVIDERS_START     = 'PROVIDERS_START',
    PROVIDERS_FAIL      = 'PROVIDERS_FAIL',
    PROVIDERS_SUCCESS   = 'PROVIDERS_SUCCESS', 
    PROVIDERS_CLEAN     = 'PROVIDERS_CLEAN',

    BILLING_CARDS_START     = 'BILLING_CARDS_START',
    BILLING_CARDS_FAIL      = 'BILLING_CARDS_FAIL',
    BILLING_CARDS_SUCCESS   = 'BILLING_CARDS_SUCCESS', 
    BILLING_CARDS_CLEAN     = 'BILLING_CARDS_CLEAN',
    
    NEW_BILLING_START     = 'NEW_BILLING_START',
    NEW_BILLING_FAIL      = 'NEW_BILLING_FAIL',
    NEW_BILLING_SUCCESS   = 'NEW_BILLING_SUCCESS', 
    NEW_BILLING_CLEAN     = 'NEW_BILLING_CLEAN',

    VERIFY_PAYMENT_START     = 'VERIFY_PAYMENT_START',
    VERIFY_PAYMENT_FAIL      = 'VERIFY_PAYMENT_FAIL',
    VERIFY_PAYMENT_SUCCESS   = 'VERIFY_PAYMENT_SUCCESS', 
    VERIFY_PAYMENT_CLEAN     = 'VERIFY_PAYMENT_CLEAN'

    